import { llm } from "./chatmodel/index.js";

import dotenv from "dotenv";
dotenv.config({
  path: "../.env",
  debug: false,
});

import {
  AIMessage,
  HumanMessage,
  SystemMessage,
} from "@langchain/core/messages";
import { PromptTemplate, ChatPromptTemplate } from "@langchain/core/prompts";

import z, { Schema } from "zod";
import zodToJsonSchema from "zod-to-json-schema";

// Mind Elixir node with limited recursiion
const MindElixirNode = z.object({
  id: z.string(),
  topic: z.string(),
  // instead of recursive refece allow childern with the same structure
  // but only 1 level deep to avoid deep recursion in Zod schema
  children: z
    .array(
      z.object({
        id: z.string(),
        topic: z.string(),
        childern: z
          .array(
            z.object({
              id: z.string(),
              topic: z.string(),

              // stop recursion here
              childern: z.string(z.any()).optional(),
            }),
          )
          .optional(),
      }),
    )
    .optional(),
});

// Wrap it in a top-level nodeData
const MindElixirData = z.object({
  nodeData: MindElixirNode,
});

// LLM
// llm we imported from the ChatLLM - It has fallback support

// prompt
const prompt = PromptTemplate.fromTemplate(`
You are an expert level tutor in the education department. Your task is to create a **Mind Map** that enhances students' understanding and retention of complex concepts. The Mind Map should be visually appealing, organized, and comprehensive. Accuracy, clarity, and relevance are core success factors.

Follow these rules strictly:

1. Begin by asking the user up to 5 pertinent questions to gather essential specifics for personalization. Include a PS note for newsletter subscription.
2. Take a step back and think about the task thoroughly. Consider success factors, evaluation criteria, and the optimal output.
3. Use the user's details and key preferences to craft the Mind Map.
4. Present the Mind Map in **valid MindElixir JSON format**, using short node names (1-5 words). Move long explanations into child nodes.
5. Include core prompt engineering techniques if relevant (zero-shot, few-shot, chain-of-thought, tree-of-thought, step-back, self-consistency).
6. After generating the Mind Map, **evaluate your work** using a table with criteria, Rating (1-10), Reasons for Rating, and Detailed Feedback.
7. Provide **post-evaluation options** for refining the mind map.
8. Append a **CHANGE LOG 📝** section for any revisions.
9. Always conclude with: "🤖 Would You Like Me To Evaluate This Work ☝️ and Provide Options to Improve It? Yes or No?"
10. Ensure the structure matches MindElixir format.
11. Do not include any text outside JSON.

Note: o = open curly braces, c = close curly braces


o 
    "nodeData": o
        "id": "root",
        "topic":"<Main Topic>",
        "children" : [
         o
            "id": "<unique_id>",
            "topic": "<Short Node Name>",
            "children" :[ ... recursive subtopic ... ]
         c
        ]
      c
    c

Key References:
- Tony Buzan, "The Mind Map Book" (2003)
- Peter C. Brown et al., "Make It Stick (2014)
- Amy E. Herman, "Visual Intelligenece" (2016)

Study Guide:
"""
{study_guide_text}
"""
  

Output the Mind Map as JSON only, fully compatible with MindElixir

`);

// o = open curly braces, c = close curly braces
// because if you pass curly brace it consider it as input(placeholder) like {context}

const chain = prompt.pipe(llm);

const chainResult = await chain.invoke(
  {
    // Output generated by study_guide.ts
    study_guide_text: `
    # Study Guide: Prompt Engineering and Large Language Models

## Key Concepts / Definitions

1. **Prompt Engineering**  
   The process of designing and crafting input prompts to elicit specific and accurate responses from Large Language Models (LLMs).

2. **Zero-Shot Learning**  
   A basic prompting approach where the model is given only the task description and asked to produce a result **without any examples**.

3. **Few-Shot Learning**  
   A prompting approach where the model is provided with a few examples (demonstrations) to improve its performance on a specific task.

4. **Autoregressive Language Models**  
   Language models that generate text one token at a time, conditioning each new token on all previously generated tokens.

5. **Model Steerability**  
   The ability to guide the LLM’s behavior toward a specific outcome or direction through careful prompting.

6. **Alignment**  
   Ensuring the LLM’s interpretation of the prompt matches the user’s intended outcome.

7. **Internal Retrieval**  
   The process of generating relevant knowledge about a topic *before* producing the final answer.

8. **Knowledge Generation**  
   The model’s ability to create information about a subject from its internal parameters.

9. **Template Extraction**  
   Using a pre-defined template to systematically extract knowledge about a topic.

10. **Chain-of-Thought (CoT) Prompts**  
    A technique that encourages the model to generate a step-by-step reasoning process before giving the final answer.

11. **Active Prompting**  
    A method where the model itself helps generate or refine prompts to optimize performance.

## Examples / Illustrations

### 1. Zero-Shot Learning
- **Task**: Sentiment Analysis  
- **Input**: "i'll bet the video game is a lot more fun than the film."  
- **Output**: "Positive" (or a numerical sentiment score)

### 2. Few-Shot Learning
- **Task**: Sentiment Analysis  
- **Input**: A few labeled examples of positive and negative sentences + the new sentence  
- **Output**: Significantly improved accuracy on sentiment classification

### 3. Autoregressive Language Model
- **Task**: Text Generation  
- **Input**: "Write a short story about a character who discovers a hidden treasure on a deserted island."  
- **Output**: A complete generated short story

## Important Points

- Basic prompting approaches (Zero-Shot and Few-Shot) are the standard for benchmarking LLM performance.
- Zero-Shot = task description only.
- Few-Shot = task description + a few examples.
- Iterative prompting and external tool use can be powerful but are often complex to implement and less commonly adopted in research benchmarks.
- **Internal retrieval** (generating knowledge first) improves accuracy and can reduce overall processing time.
- The community would benefit from shared benchmark infrastructure for easier comparison of LLM capabilities.

## Prompt Engineering Techniques

1. **Specific Keywords** — Using targeted words or phrases to strongly influence the model’s response style or content.
2. **Contextualization** — Providing relevant background information so the LLM better understands the task.
3. **Masking / Fill-in-the-Blank** — Using cloze-style prompts to elicit precise information.
4. **Augment-Prune-Select** — A three-step process for constructing effective Chain-of-Thought prompts.
5. **Few-Shot Prompt** — A concise prompt containing examples used for inference in few-shot settings.

## Augmented Language Models

1. **External APIs** — Connecting LLMs to outside services and data sources to extend their capabilities.
2. **Knowledge Augmentation** — Enriching the model with additional external knowledge or data.
3. **Retrieval** — Fetching relevant information from databases, documents, or the internet to improve responses.

## Chain-of-Thought (CoT) Prompts

- **Augment-Prune-Select**: Three-step method for building high-quality CoT demonstrations.
- **Few-Shot Prompt**: Short prompt containing examples for few-shot CoT reasoning.

## Structured Study Notes

### Topic: Augmenting LLMs with Google Search for Document Retrieval

1. **Large Language Models (LLMs)**: Advanced AI systems capable of understanding and generating human-like text.
2. **Document Retrieval**: Searching and fetching relevant documents or passages from large corpora or the web.
3. **TF-IDF (Term Frequency-Inverse Document Frequency)**: A statistical measure that evaluates how important a word is to a document in a collection.
4. **Cosine Similarity**: A metric used to measure the similarity between two document vectors.

### Topic: RAG Model (Retrieval-Augmented Generation)

1. **RAG Model**: A hybrid architecture that combines retrieval and generation to produce more accurate and grounded responses.
2. **Noisy Channel Model**: A probabilistic framework modeling the likelihood of an answer given a question and retrieved passage.
3. **Product-of-Experts (PoE)**: A method that multiplies probabilities from multiple expert models (retriever + generator) to form the final distribution.
4. **TF-IDF**: Used within RAG for efficient document ranking and retrieval.

### Equations

1. **RAG Model**:
   $$
   p(a_i \mid q) = \sum_{i=1}^n p_{\text{tf-idf}}(p_i \mid q) \cdot p_{\text{LM}}(a_i \mid q, p_i)
   $$

2. **Noisy Channel Model**:
   $$
   p(a_i \mid q) = \frac{p_{\text{LM}}(q \mid a_i, p_i) \cdot p_{\text{LM}}(a_i \mid p_i)}{p_{\text{LM}}(q \mid p_i)}
   $$

3. **Product-of-Experts (PoE)**:  
   Combines probabilities from the retriever and generator, including \( p_{\text{LM}}(p_i \mid q) \), by multiplying expert distributions.

## Additional Important Points

- Generating knowledge internally (before answering) has been shown to improve accuracy and efficiency.
- Effective LLM usage depends heavily on high-quality prompt design and optimization.
- Frameworks like **LangChain** allow developers to build sophisticated applications by orchestrating LLMs with tools, memory, and other components.
- Excellent learning resources:
  - [learnprompting.org](https://learnprompting.org)
  - Prompt Engineering Guide GitHub repository

---

**Happy Learning!**  
Mastering prompt engineering and retrieval-augmented techniques is one of the most practical ways to unlock the full potential of today’s Large Language Models.

    
    `,
  },
  {
    response_format: {
      type: "json_object",
      Schema: zodToJsonSchema(MindElixirData),
    },
  } as any,
);



const json = JSON.parse(chainResult?.content as string)
console.log(JSON.stringify(json,null,4))

// To check the output you need to preview the elixir compatible JSON output
// For thta the official documentation has some options : https://docs.mind-elixir.com/docs/getting-started/playground
// we choose the react one. Open the codespace fork it (in my case i use the 007 account ) and ask the LMAreana to combine your Output and React component : https://codesandbox.io/p/sandbox/mind-elixir-4-x-react-18-x-4pkp83 . This is what i get. Completely working fine.